CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Crear tabla de usuarios
CREATE TABLE IF NOT EXISTS usuarios (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash TEXT,
  nombre VARCHAR(255),
  role VARCHAR(50) NOT NULL DEFAULT 'USER',
  google_id VARCHAR(255) UNIQUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Crear tabla de categorías
CREATE TABLE IF NOT EXISTS categorias (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Crear tabla de productos
CREATE TABLE IF NOT EXISTS productos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre VARCHAR(255) NOT NULL,
  categoria_id UUID NOT NULL REFERENCES categorias(id) ON DELETE RESTRICT,
  marca VARCHAR(255),
  modelo VARCHAR(255),
  numero_serie VARCHAR(255),
  cantidad_total INTEGER NOT NULL,
  cantidad_disponible INTEGER NOT NULL,
  unidad VARCHAR(50),
  metraje_total INTEGER,
  metraje_restante INTEGER,
  ubicacion VARCHAR(255),
  estado VARCHAR(50) DEFAULT 'nuevo',
  activo_fijo VARCHAR(255),
  dependencia_codigo VARCHAR(100),
  dependencia_nombre VARCHAR(255),
  stock_estado VARCHAR(50) DEFAULT 'normal',
  fecha_adquisicion DATE,
  foto_url TEXT,
  descripcion TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Crear tabla de archivos
CREATE TABLE IF NOT EXISTS archivos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  producto_id UUID NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
  nombre VARCHAR(255) NOT NULL,
  mime_type VARCHAR(100),
  drive_file_id VARCHAR(255) NOT NULL,
  web_view_link TEXT,
  web_content_link TEXT,
  uploaded_at TIMESTAMP DEFAULT NOW()
);

-- Crear tablas de órdenes de trabajo
CREATE TABLE IF NOT EXISTS ordenes_trabajo (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  titulo VARCHAR(255) NOT NULL,
  descripcion TEXT,
  secuencia BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  numero VARCHAR(50) UNIQUE,
  usuario_id UUID NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  mantis_ticket VARCHAR(255),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ot_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  orden_id UUID NOT NULL REFERENCES ordenes_trabajo(id) ON DELETE CASCADE,
  producto_id UUID NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
  cantidad INTEGER NOT NULL DEFAULT 0,
  metraje_usado INTEGER,
  cable_descripcion TEXT
);

CREATE TABLE IF NOT EXISTS reportes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tipo VARCHAR(100) NOT NULL,
  titulo VARCHAR(255) NOT NULL,
  descripcion TEXT,
  archivo_url TEXT,
  creado_por UUID REFERENCES usuarios(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Crear índices para mejorar rendimiento
CREATE INDEX idx_productos_categoria ON productos(categoria_id);
CREATE INDEX idx_productos_nombre ON productos(nombre);
CREATE INDEX idx_productos_estado ON productos(estado);
CREATE INDEX idx_productos_dependencia ON productos(dependencia_codigo);
CREATE INDEX idx_archivos_producto ON archivos(producto_id);
CREATE INDEX idx_ordenes_usuario ON ordenes_trabajo(usuario_id);
CREATE INDEX idx_ordenes_fecha ON ordenes_trabajo(created_at);
CREATE INDEX idx_ot_items_orden ON ot_items(orden_id);
CREATE INDEX idx_ot_items_producto ON ot_items(producto_id);

-- Crear algunas categorías iniciales
INSERT INTO categorias (nombre) VALUES
  ('Servidores'),
  ('Switches de Red'),
  ('Routers'),
  ('Cables de Red'),
  ('Monitores'),
  ('Teclados y Ratones'),
  ('Fuentes de Poder'),
  ('Placas Madre'),
  ('Memorias RAM'),
  ('Discos Duros'),
  ('SSD'),
  ('Procesadores'),
  ('Tarjetas Gráficas'),
  ('Módems'),
  ('Access Points WiFi'),
  ('Firewall'),
  ('UPS'),
  ('Licencias Software'),
  ('Accesorios Varios'),
  ('Herramientas Técnicas')
ON CONFLICT DO NOTHING;
